# Generated by Django 4.1.3 on 2022-11-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
