# Generated by Django 4.0.5 on 2022-11-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_game_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='string',
            new_name='game_string',
        ),
    ]
